apiVersion: v1
kind: Deployment
metadata:
	name: restrictednginx
spec:
 	replicas: 5
	template:
		kind: Pod
		metadata:
			creationTimestamp: null
			labels:
				run: lab4
			name: lab4
		spec:
			securityContext:
				runAsNonRoot: true
			containers:
				- image: nginx
					name: lab4
					resources:
						requests:
							memory: "64Mi"
							cpu: "125m"
						limits:
							memory: "256Mi"
							cpu: "250m"
					dnsPolicy: ClusterFirst
				restartPolicy: Always
		status: {}
