apiVersion: v1
kind: Pod
metadata:
	creationTimestamp: null
	labels:
	run: ngsecure
	name: ngsecure
spec:
	securityContext:
		runAsNonRoot: true
	containers:
		- image: nginx
			name: ngsecure
			resources: {}
		dnsPolicy: ClusterFirst
		restartPolicy: Always
status: {}
